# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\202300376\PycharmProjects\pythonProject\venv\Lib\site-packages\qt5_applications\Qt\bin\대손충당금 계산.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1203, 813)
        Dialog.setMouseTracking(False)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 861, 721))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_11.setGeometry(QtCore.QRect(30, 30, 151, 51))
        self.textBrowser_11.setLineWrapColumnOrWidth(0)
        self.textBrowser_11.setTabStopWidth(80)
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_12.setGeometry(QtCore.QRect(30, 90, 151, 51))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 150, 121, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_6.setGeometry(QtCore.QRect(630, 100, 111, 31))
        self.checkBox_6.setObjectName("checkBox_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(480, 330, 121, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_13.setGeometry(QtCore.QRect(200, 330, 261, 51))
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(480, 90, 121, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_14.setGeometry(QtCore.QRect(200, 150, 261, 51))
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_15.setGeometry(QtCore.QRect(30, 210, 151, 51))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_7.setGeometry(QtCore.QRect(630, 340, 111, 31))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_8.setGeometry(QtCore.QRect(630, 220, 111, 31))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_9.setGeometry(QtCore.QRect(630, 40, 111, 31))
        self.checkBox_9.setObjectName("checkBox_9")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_16.setGeometry(QtCore.QRect(200, 90, 261, 51))
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_17.setGeometry(QtCore.QRect(30, 330, 151, 51))
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_18.setGeometry(QtCore.QRect(200, 30, 261, 51))
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.progressBar_3 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_3.setGeometry(QtCore.QRect(30, 490, 611, 16))
        self.progressBar_3.setProperty("value", 50)
        self.progressBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setObjectName("progressBar_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(480, 210, 121, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.textBrowser_19 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_19.setGeometry(QtCore.QRect(30, 150, 151, 51))
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_10.setGeometry(QtCore.QRect(630, 160, 111, 31))
        self.checkBox_10.setObjectName("checkBox_10")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab)
        self.pushButton_10.setGeometry(QtCore.QRect(480, 30, 121, 51))
        self.pushButton_10.setObjectName("pushButton_10")
        self.progressBar_4 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_4.setGeometry(QtCore.QRect(30, 460, 611, 16))
        self.progressBar_4.setProperty("value", 50)
        self.progressBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_4.setInvertedAppearance(False)
        self.progressBar_4.setObjectName("progressBar_4")
        self.textBrowser_20 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_20.setGeometry(QtCore.QRect(200, 210, 261, 51))
        self.textBrowser_20.setObjectName("textBrowser_20")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 527, 131, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(50, 567, 221, 16))
        self.label_2.setObjectName("label_2")
        self.textBrowser_21 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_21.setGeometry(QtCore.QRect(30, 270, 151, 51))
        self.textBrowser_21.setObjectName("textBrowser_21")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_11.setGeometry(QtCore.QRect(630, 280, 111, 31))
        self.checkBox_11.setObjectName("checkBox_11")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab)
        self.pushButton_11.setGeometry(QtCore.QRect(480, 270, 121, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(210, 280, 101, 31))
        self.label_9.setObjectName("label_9")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(320, 280, 141, 31))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser_22 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_22.setGeometry(QtCore.QRect(200, 390, 261, 51))
        self.textBrowser_22.setObjectName("textBrowser_22")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_12.setGeometry(QtCore.QRect(630, 400, 111, 31))
        self.checkBox_12.setObjectName("checkBox_12")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab)
        self.pushButton_12.setGeometry(QtCore.QRect(480, 390, 121, 51))
        self.pushButton_12.setObjectName("pushButton_12")
        self.textBrowser_23 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_23.setGeometry(QtCore.QRect(30, 390, 151, 51))
        self.textBrowser_23.setObjectName("textBrowser_23")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 564, 93, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(50, 600, 221, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 597, 93, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(50, 637, 221, 16))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(360, 563, 291, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(360, 600, 411, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(360, 630, 411, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listView = QtWidgets.QListView(self.tab_2)
        self.listView.setGeometry(QtCore.QRect(350, 10, 481, 661))
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 301, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 90, 301, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 150, 301, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 300, 131, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(40, 330, 201, 41))
        self.label_6.setObjectName("label_6")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(250, 340, 93, 21))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(40, 390, 271, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(40, 450, 271, 41))
        self.label_8.setObjectName("label_8")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 210, 301, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(40, 500, 161, 41))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser_11.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">#1 (기초)</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">데이터 이관</p></body></html>"))
        self.textBrowser_12.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">#2 (당월)</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">데이터 이관</p></body></html>"))
        self.pushButton_6.setText(_translate("Dialog", "Run"))
        self.checkBox_6.setText(_translate("Dialog", "오류검증"))
        self.pushButton_7.setText(_translate("Dialog", "Run"))
        self.textBrowser_13.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">36개월 평균 Roll-rate 설정 및<br />구간별 대손률 계산</p></body></html>"))
        self.pushButton_8.setText(_translate("Dialog", "당월 Upload"))
        self.textBrowser_14.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">전월 대손정보</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">데이터 sheet에 불러오기</p></body></html>"))
        self.textBrowser_15.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">#4 (당월)</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">채권분류 입력</p></body></html>"))
        self.checkBox_7.setText(_translate("Dialog", "오류검증"))
        self.checkBox_8.setText(_translate("Dialog", "오류검증"))
        self.checkBox_9.setText(_translate("Dialog", "오류검증"))
        self.textBrowser_16.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">당월 채권원장 </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">데이터 sheet에 불러오기</p></body></html>"))
        self.textBrowser_17.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">#5 Roll-rate 실행</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">대손률 계산</p></body></html>"))
        self.textBrowser_18.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">기초 대손충당금 잔액 및 </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">거래처 정보 불러오기</p></body></html>"))
        self.pushButton_9.setText(_translate("Dialog", "Run"))
        self.textBrowser_19.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">#3 (전월)</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">채권분류 입력</p></body></html>"))
        self.checkBox_10.setText(_translate("Dialog", "오류검증"))
        self.pushButton_10.setText(_translate("Dialog", "전월 Upload"))
        self.textBrowser_20.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">당월 거래처정보<br />데이터 sheet에 입력</p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">■ 체크사항</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "#1. 전월파일 업로드 양식"))
        self.textBrowser_21.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">#4 최종구간</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">채권반제금액</p></body></html>"))
        self.checkBox_11.setText(_translate("Dialog", "오류검증"))
        self.pushButton_11.setText(_translate("Dialog", "Save"))
        self.label_9.setText(_translate("Dialog", "잔여금액 조회"))
        self.textBrowser_22.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">36개월 평균 Roll-rate 설정 및<br />구간별 대손률 계산</p></body></html>"))
        self.checkBox_12.setText(_translate("Dialog", "오류검증"))
        self.pushButton_12.setText(_translate("Dialog", "Run"))
        self.textBrowser_23.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">#6 최종정산 표<br />업데이트</p></body></html>"))
        self.pushButton_4.setText(_translate("Dialog", "Template_1"))
        self.label_3.setText(_translate("Dialog", "#2. 당월파일 업로드 양식"))
        self.pushButton_5.setText(_translate("Dialog", "Template_2"))
        self.label_4.setText(_translate("Dialog", "#3. 당월파일 업로드 양식"))
        self.label_10.setText(_translate("Dialog", "#4. 채권분류 SAP 업로드(ZFIKRR2030)"))
        self.label_11.setText(_translate("Dialog", "#5.전분기 33개월 ~ 36개월 구간채권 채권의 미회수 금액"))
        self.label_12.setText(_translate("Dialog", "#6.업데이트 후, 엑셀파일 생성(저장위치 : 바탕화면)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Roll-rate"))
        self.pushButton.setText(_translate("Dialog", "#1. 전기말 손상거래처 Upload"))
        self.pushButton_2.setText(_translate("Dialog", "#2. 당기 채권회수 업데이트"))
        self.pushButton_3.setText(_translate("Dialog", "#3. 당기 신규손상 거래처 업데이트"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">■ 체크사항</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p>#1. 전기말 내역 업로드<br/>     -&gt; 오른쪽 화면 일치여부 확인</p></body></html>"))
        self.pushButton_13.setText(_translate("Dialog", "Template_3"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p>#2. 손상거래처 당기말기준 회수현황<br/>-&gt; 한국사업부 채권담당과 확인</p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p>#3. 연말기준 신규손상 거래처 업데이트<br/>-&gt; 한국사업부 채권담당과 확인</p></body></html>"))
        self.pushButton_14.setText(_translate("Dialog", "#4. 개별손상채권 현황표 업데이트"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p>#4. 엑셀파일 생성</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "개별손상채권"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
